# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: ankane/pgvector:v0.5.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
