import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="container mx-auto p-4 max-w-[40rem]">
      <h1 className="text-3xl font-bold text-center my-4">
        Terms and Conditions
      </h1>
      <div className="text-justify text-gray-700">
        <p>
          These terms and conditions outline the rules and regulations for the
          use of Omlete&apos;s Website, located at omlete.com.
        </p>
        <p>
          By accessing this website, we assume you accept these terms and
          conditions. Do not continue to use Omlete if you do not agree to all
          of the terms and conditions stated on this page.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">1. Definitions</h2>
        <ul className="list-disc pl-5">
          <li>
            <strong>&quot;Service&quot;:</strong> The recipe generation service
            provided by Omlete through our website.
          </li>
          <li>
            <strong>&quot;Content&quot;:</strong> All material generated by our
            Service, including AI-generated recipes.
          </li>
          <li>
            <strong>&quot;Coins&quot;:</strong> Virtual currency used on our
            website to access the Service.
          </li>
        </ul>

        <h2 className="text-xl font-semibold mt-5 mb-2">
          2. Account Registration
        </h2>
        <p>
          Users must register an account through Google OAuth to use our
          Service. By creating an account, you agree to provide accurate and
          complete information and to keep this information updated.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">
          3. Virtual Currency (Coins)
        </h2>
        <p>
          Coins are required to use the Service. Users receive a complimentary
          amount upon registration and can purchase additional Coins. For any
          reason, you can request a refund within 7 days of your purchase if all
          purchased coins are unspent. If you are not satisfied with the
          product, then let me know and I will refund your purchase right away.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">
          4. Use of the Service
        </h2>
        <p>
          The Service allows users to generate recipes based on inputted
          ingredients or recipe names. The generated recipes are considered
          proprietary content of Omlete.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">
          5. Intellectual Property Rights
        </h2>
        <p>
          The Content generated by our Service, including but not limited to
          recipes, is the property of Omlete and protected by copyright laws.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">
          6. Limitation of Liability
        </h2>
        <p>
          Omlete is not responsible for the accuracy, safety, or dietary
          suitability of any recipe generated by our Service. Users must
          exercise their own judgment and verify the safety and suitability of
          recipes for human consumption.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">
          7. User Responsibilities
        </h2>
        <p>
          Users must not input any material into the Service that is illegal,
          offensive, or violates any third-party rights. Misuse of the platform
          may result in account termination.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">
          8. Amendments to Terms and Conditions
        </h2>
        <p>
          Omlete reserves the right to modify these terms and conditions at any
          time. Such changes will be effective upon posting on our website.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">9. Governing Law</h2>
        <p>
          These terms and conditions shall be governed and construed in
          accordance with the laws of the United Kingdom, without regard to its
          conflict of law provisions.
        </p>

        <h2 className="text-xl font-semibold mt-5 mb-2">
          10. Contact Information
        </h2>
        <p>
          For any questions or inquiries regarding these terms, please contact
          me at alex@eatomlete.com.
        </p>
      </div>

      <div className="mt-12 text-sm">Last updated: 18 November 2023</div>
    </div>
  );
};

export default TermsAndConditions;
